os: linux
language: bash
services:
  - docker

env: 
  global:
    - DOCKER_REPO="zielonafabryka/ffmpeg"
    
stages:
  - build

before_install:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin

jobs:
  include:
    - stage: build
      name: "ffmpeg Zielona Fabryka"
      script: 
        - docker build -t $DOCKER_REPO:latest .
        - if [ "$TRAVIS_BRANCH" = "master" ]; then docker push $DOCKER_REPO; fi
    